var JS_CITIES_DATA = 
[
"----- PERSONAL TIMES -------------------",
"00.000.PERSONAL",

"----- SAUDI ARABIA ---------------------",
"SA.ِABU-ARISH.    أبوعريش",
"SA.ِADUM.      أضم",
"SA.ِAHADRUFIDAH.   أحد رفيده",
"SA.ِِِAL-ARADIA-ALSHMALYAH.  العرضيه الشماليه",
"SA.Al-BASHAIR.   البشائر",
"SA.ِAL-DAWADMI.   الدوادمي",
"SA.ِAL-KHAFJI.    الخفجي",
"SA.ِAL-KHURMA.     الخرمه",
"SA.ِAL-MAJARDAH.  المجارده",
"SA.ِAL-MAJMAAH. المجمعه",
"SA.ِAL-MANDAQ.      المندق",
"SA.AlQouz.    القوز",
"SA.ِAL-QUAIEIA.   القويعيه",
"SA.ِAL-QUNFUTHA.     القنفذه ",
"SA.ALRAS.    الرس",
"SA.ِALBKIRIA.  البكيريه",
"SA.ِALFARAA.   الفرعاء",
"SA.ِBAISH.     بيش",
"SA.ِBALJURASHY.  بالجرشي",
"SA.ِKHAIBAR.   خيبر",
"SA.ِKHLAIS.  خليص",
"SA.ِMAHAIL-ASEER.  محايل عسير",
"SA.ِRABIGH.  رابغ",
"SA.ِRAFHA.    رفحاء",
"SA.ِSABIA.   صبيا",
"SA.SABTALALAYA.   سبت العلايا",
"SA.ِSHARORA.  شروره",
"SA.ِSHAGRA.   شقراء",
"SA.ِSURATOBIDAH.  سراة عبيدة",
"SA.Abha. أبها",
"SA.ABGAIG. أبقيق",
"SA.AFLAJ. أﻷفلاج",
"SA.AHAD-ALMASARRIHA. أحد ألمسارحه",
"SA.AlQUNFUTHA. القنفذه",
"SA.AL-AGEEG.  العقيق",
"SA.AL-AHASA. الاحساء",
"SA.AL-BAHAH.الباحه",
"SA.AL-DULAM.الدلم",
"SA.AL-KHARJ.  الخرج",
"SA.AL-KHUBAR.الخبر",
"SA.AL-LITH.الليث",
"SA.AL-MADINAH.المدينه المنوره",
"SA.AL-NAMAS. النماص",
"SA.AL-QASSIM.القصيم",
"SA.AL-QURAYAT.  القريات",
"SA.AL-TAIF. الطايف",
"SA.AL-ZULFI. الزلفي",
"SA.ALARIDAH.   العارضه",
"SA.ALASHTA.   الاشتاء",
"SA.ALDARB.   الدرب",
"SA.ALSHUBA.   الشعبه",
"SA.ALULA.  العلا",
"SA.ALWADIYAIN.  الواديين",
"SA.ARAR.عرعر",
"SA.BADEASHAMALI.  البدائع الشماليه",
"SA.BAHRA. بحره",
"SA.BISHA.    بيشه",
"SA.BURAYDAH.  بريده",
"SA.DAHARAN.   الظهران",
"SA.ِDAHRAN-ALJANUB. ظهران الجنوب",
"SA.DAMMAM.الدمام",
"SA.DHARMA.  ضرما",
"SA.FARASAN.   فرسان",
"SA.HAFAR-BATIN.حفر الباطن",
"SA.HAIL. حايل",
"SA.HOTAT-BANITAMIM.حوطة بني تميم",
"SA.HURYMILA. حريملاء",
"SA.JAZAN.جازان",
"SA.JEDDAH.جده",
"SA.JUBAIL.الجبيل",
"SA.KHAMIS-MUSHAIT. خميس مشيط",
"SA.LAYLA. ليلا",
"SA.MAKKAH.مكه",
"SA.MASTORAH.  مستوره",
"SA.MUDILEEF.  المظيليف",
"SA.NAJRAN.نجران",
"SA.REJAL-ALMAA.   رجال المع",
"SA.RIYADH.الرياض",
"SA.SAJIR.   ساجر",
"SA.SKAKA.   سكاكا",
"SA.SWAIDAN-ALAFLAJ.  سويدان الافلاج",
"SA.TABOUK. تبوك",
"SA.THURB.   ثرب",
"SA.TURAIF.   طريف",
"SA.UMLUJ.املج",
"SA.UNIZAH.   عنيزه",
"SA.WADI-ALDAWASER.وادي الدواسر",
"SA.YANBU.ينبع",

"----- ALGERIA ------------------------------",
"DZ.ALGERIA.   الجزائر",
"DZ.ADRAR. أدرار",
"DZ.CONSTANTINE.    قسنطينه",
"DZ.KAIS.  قايس",
"DZ.SIDI_OKBA.  سيدي عقبة",
"DZ.Tamelahet-tissemsilt. تملاحت",

"----- EGYPT ------------------------------",
"EG.ASSUIT.   أسيوط",
"EG.DIKIRNIS. الدقهليه",
"EG.ZAGAZIG.الزقازيق‎",

"----- IRAQ ------------------------------",
"IQ.ASULAYMANIYA.  السليمانيه",

"----- JORDAN ------------------------------",
"JO.AMMAN. عمان",
"JO.KARAK. كرك",
"JO.MAAN.   معان",
"JO.MUTAH.  مؤته",


"----- LIBYA ------------------------------",
"LY.ABARIQAH.   البريقة",
"LY.Aljaghbub. الجغبوب",
"LY.Almarag.    المرج",
"LY.ALBAYDAA.    البيضاء",
"LY.ALKAFRAH.    الكفرة",
"LY.ALKHUMS.    الخمس",
"LY.ALZAWIAH.    الزاوية",
"LY.AWJALH.    أوجله",
"LY.BanyWalead.   بني وليد",
"LY.Benghazi.    بنغازي",
"LY.Benjuwad.    بن جواد",
"LY.DARNAH.    درنة",
"LY.Ajdabiya.  اجدابيا",
"LY.Ekdames.    غدامس",
"LY.Emsaed.   امساعد",
"LY.Hoon.    هون",
"LY.Jalo.   جالو",
"LY.MISRATA.    مصراته",
"LY.Naloot.    نالوت",
"LY.Raslanof.   رأس لانوف",
"LY.SABHA.    سبها",
"LY.SERT.    سرت",
"LY.Shahat.   شحات",
"LY.Tobrek.    طبرق",
"LY.TRIPOLI.   طرابلس",
"LY.Ubari.   أوباري",
"LY.ZLITEN.    زليتن",

"----- KUWAIT ------------------------------",
"KW.KUWAIT.  الكويت",

"----- OMAN ------------------------------",
"OM.Alawabi.  الاوابي",
"OM.Alkhabora. الخابوره",
"OM.AL-ASKHARA.  أشخره",
"OM.ALBRIMI.     البريمي",
"OM.ALRESTAG.   الرستاق",
"OM.AZKA. أزكى",
"OM.Bahlaa.   بهلا",
"OM.BARKA-Al Billa.  باركا البيلا",
"OM.BIDBID.  بدبد",
"OM.DANAK.  ضنك",
"OM.EBRAA.   إبراء",
"OM.EBRY.    عبري",
"OM.JِAALAN_BOHASAN.  جعلان بو حسن",
"OM.JEALAN_BOALI.    جعلان بوعلي",
"OM.AL-KHWAIR.  الخوير",
"OM.LIWA.   لوى",
"OM.MAHDAH.    محضه",
"OM.MASNAA.  مصنعة",
"OM.MUSCAT.مسقط",
"OM.Nakhl. نخل",
"OM.Nazawi.  النزاوي",
"OM.Qariat.  قريات",
"OM.Samael.  سمايل",
"OM.SAHAR.    صحار",
"OM.SALALA.  صلاله",
"OM.SAMAD-ALSHAN. سمد ألشان",
"OM.SUHUM.   صحم",
"OM.SUR.  صور",
"OM.SWAIK.  سويق",
"OM.Badia.بدية",
"OM.Bakha.بخاء",
"OM.Fahood.فهود",
"OM.Haima.هيما",
"OM.Madha.مدحاء",
"OM.Mahwat.محوت",
"OM.Manh.منح",
"OM.Maseera.مصيرة",
"OM.QarnAlalam.قرن العلم",
"OM.RasAlhad.رأس الحد",
"OM.Sadah.سدح",
"OM.Sanaw.سناو",
"OM.Sarab.صراب",
"OM.Sarfit.صرفيت",
"OM.Shanas.شناص",
"OM.Taka.طاقة",
"OM.Thamreet. ثمريت",
"OM.WadiBaniKhaled.وادي بني خالد",
"OM.Yanqul.ينقل",
"OM.Adam.أدم",
"OM.Albarimi.البريمي",
"OM.Aldakm.الدقم",
"OM.Algazer.قلهات",
"OM.Alhamra.الحمراء",
"OM.AlkabelEast.القابل الشرقيه",
"OM.Alkamel.الكامل",
"OM.Almadibi.المضيبي",






"----- SYRIA------------------------------",
"SY.SِANAMIN.  صنمين",

"----- TUNISIA ------------------------------",
"TN.BINQRAN.  بن قران",
"TN.GERGEIS.   جرجيس",
"TN.GIBLY.      قبلي",
"TN.HERAGLA.    هرقلة",
"TN.MARETH.  ماريس",

"----- YAMEN ------------------------------",
"YE.MUKALLA.المكلا",
"YE.QARYO.  قريو حضرموت",
"YE.TAIZ.  تعز",

"----Palestinian Territory---------------------------------",
"PS.Akka.        عكا ", 
"PS.Baysan.     بيسان", 
"PS.Beersheba.     بئر السبع", 
"PS.Bethlehem.    بيت لحم", 
"PS.DeirAalBalah.    دير البلح", 
"PS.Gaza.      غزه", 
"PS.Haifa.     حيفا", 
"PS.HEBRON.الخليل",
"PS.Jaffa.    يافا", 
"PS.Jenin.    جنين", 
"PS.Jericho.    اريحا", 
"PS.Jerusalem.    القدس", 
"PS.KhanYunis.  خان يونس",
"PS.Lod.     اللد", 
"PS.Nablus.     نابلس", 
"PS.Nazareth.   ألناصرة",
"PS.Qalqilya.    قلقيلية", 
"PS.Rafah.     رفح", 
"PS.Ramallah.     رام الله", 
"PS.Ramla.     الرملة", 
"PS.safad.     صفد",
"PS.Tayibe-KufurKassem.    كفر قاسم-الطيبة", 
"PS.Tiberias.     طبريا", 
"PS.Tulkarm.    طولكرم", 
"PS.Umm al-Fahm.    ام الفحم",

"----- INDONISIA ------------------------------",
"ID.JAKARTA.   جاكرتا",

"----- ETHIOPIA ---------------------------",
"ET.GOJJAM.قوجام",

"----- KENYA---------------------------",
"KE.NAIROBI.  كينيا",



"----- AUSTRALIA ------------------------------",
"AU.MELBOURNE.  ملبورن",

"----- CANADA ------------------------------",
"CA.VANCOUVER.",



"---- DANMARK---------------------------------",
"DK.AARHUS.أرهوس",

"----- FRANCE ----------------------------",
"FR.BELLEGARDE SUR VALSERINE.",
"FR.FURIANI. FURIANI",
"FR.GRENOBLE.  FR  ",
"FR.Horaires.",
"FR.LYON-BRON.FR69",
"FR.PROPRIANO.بروبريانو",
"FR.ST-ETIENNE-2.LOIRE",
"FR.ST-ETIENNE.FR42",

"----- HOLLAND ----------------------------",
"NL.HEGEN.-",

"----ITALY ---------------------------------",
"IT.SCHIO. ",
"IT.SERRAMAZONI. ",

"---- NEW ZEALAND---------------------------------",
"NZ.AUCKLAND.أوكلاند",

"----SPAIN ---------------------------------",
"ES.BARCELONA. برشلونه ",
"ES.CABANES.  ",
"ES.DURANGO.   ",
"ES.EIBAR.  ",
"ES.SANTHILARI.",
"ES.SOCUELLAMOS.SOC",

"----SVERIGE ---------------------------------",
"SV.Alingsas.",
"SV.Amal.",
"SV.Avesta.",
"SV.Bengtsfors.",
"SV.Boden.",
"SV.Bollnas.",
"SV.Boras.",
"SV.Borlange.",
"SV.Eksjo.",
"SV.Enkoping.",
"SV.Eskilstuna.",
"SV.Eslov.",
"SV.Falkenberg.",
"SV.Falkoping.",
"SV.Filipstad.",
"SV.Flen.",
"SV.Gavle.",
"SV.Gislaved.",
"SV.Gnosjo.",
"SV.GOTEBORG.",
"SV.Halmstad.",
"SV.Haparanda.",
"SV.Harnosand.",
"SV.Hassleholm.",
"SV.Helsingborg.",
"SV.Hogsby.",
"SV.Hudiksvall.",
"SV.Hultsfred.",
"SV.Jokkmokk.",
"SV.Jonkoping.",
"SV.Kalmar.",
"SV.Karlskoga.",
"SV.Karlskrona.",
"SV.Karlstad.",
"SV.Katrineholm.",
"SV.Kiruna.",
"SV.Koping.",
"SV.Kristianstad.",
"SV.Kristinehamn.",
"SV.Landskrona.",
"SV.Lessebo.",
"SV.Lidkoping.",
"SV.Linköping. ",
"SV.Ludvika.",
"SV.Lulea.",
"SV.Lund.",
"SV.Malmo.",
"SV.Mariestad.",
"SV.Marsta.",
"SV.Mellerud.",
"SV.Mjolby.",
"SV.Monsteras.",
"SV.Nassjo.",
"SV.Norrkoping.",
"SV.Norrtalje.",
"SV.Nybro.",
"SV.Nykoping.",
"SV.Orebro.",
"SV.Ornskoldsvik.",
"SV.Oskarshamn.",
"SV.Ostersund.",
"SV.Oxelosund.",
"SV.Pajala.",
"SV.Pitea.",
"SV.Ronneby.",
"SV.Sala.",
"SV.Savsjo.",
"SV.Simrishamn.",
"SV.Skara.",
"SV.Skelleftea.",
"SV.Skovde.",
"SV.Soderhamn.",
"SV.Sodertalje.",
"SV.Solleftea.",
"SV.Stockholm.",
"SV.Strangnas.",
"SV.Sundsvall.",
"SV.Tierp.",
"SV.Tranemo.",
"SV.Trelleborg.",
"SV.Trollhattan.",
"SV.Uddevalla.",
"SV.Ulricehamn.",
"SV.Umea.",
"SV.Uppsala.",
"SV.Vanersborg.",
"SV.Varberg.",
"SV.Varnamo.",
"SV.Vasteras.",
"SV.Vastervik.",
"SV.Vaxjo.",
"SV.Vetlanda.",
"SV.Visby.",
"SV.Ystad.",


"----UNITED KINGDOME ---------------------------------",
"UK.London.لندن",


"----USA ---------------------------------",
"US.HAMTRAMCK.  ",

"----GERMANY ---------------------------------",
"DE.friedrichshafen. ",
"DE.KEHI.",
"DE.MEPPEN.",
"DE.Osnabrueck.",
"DE.PAPENBURG.  ",
"DE.Ravensburg.  ",
];